config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  resources :review_scheduled_tasks
  resources :tasks
  resources :profile_teams
  resources :requests
  resources :categories
  resources :deeds do
    collection do
    match 'search' => 'welcome#search', via: [:get, :post], as: :search
    end
  end
  resources :areas

  get 'welcome/noticias'
  get 'welcome/home'
  get 'welcome/hitos'
  get 'welcome/proyectos'
  get 'welcome/contingencia'
  get 'welcome/equipo'
  get 'welcome/administracion'
  

 devise_for :users
 
   root 'welcome#home'
   
  
    

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/area.rb
class Area < ActiveRecord::Base
    
    has_many :deeds
    has_many :requests
    has_many :blogs
end

app/models/blog.rb
class Blog < ActiveRecord::Base
    
  validates_presence_of :title, :fecha, :noticia, :category_id
  #validates_processing_of :foto,
  validate :image_size_validation
 
  mount_uploader :foto, FotoUploader
  
  belongs_to :category, foreign_key: "category_id"
  belongs_to :user, foreign_key: "user_id"
  
  
  private
  def image_size_validation
    errors[:foto] << "should be less than 500KB" if foto.size > 0.5.megabytes
  end
  
  
  
end

app/models/category.rb
class Category < ActiveRecord::Base
    
    has_many :blogs
end

app/models/deed.rb
class Deed < ActiveRecord::Base
    
    validates_presence_of :title, :date_deed, :benefit, :area_id
    validates_length_of :title, :minimum => 3
    
    belongs_to :area, foreign_key: "area_id"
    belongs_to :user, foreign_key: "id_user"
    default_scope -> { order(date_deed: :desc) }
    

  def publish_month
    date_deed.strftime("%B %Y")
  end
  def week
   date_deed.strftime('%Y-%W')
  end
  
end

app/models/profile_team.rb
class ProfileTeam < ActiveRecord::Base
    
    validates :name, presence: true
    validates :email, presence: true
    validates :anexo, presence: true
    
    
    mount_uploader :image, ImageUploader
end

app/models/request.rb
class Request < ActiveRecord::Base
    
    mount_uploader :image, ImageUploader
    
    validates :title, presence: true
    validates :area_id, presence: true
    validates :usuario, presence: true
    validates :description, presence: true
    validates :date_request, presence: true
    
    validates_presence_of   :image
    validates_integrity_of  :image
    validates_processing_of :image 
    
    belongs_to :area, foreign_key: "area_id"
    
    private
    def image_size_validation
      errors[:image] << "debe ser inferior a 1000 KB" if image.size > 1.0.megabytes
    end
   
end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  mount_uploader :image, ImageUploader
  #mount_uploader :image, ImageUploader
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :timeoutable

  # User Avatar Validation
  validates_presence_of   :image
  validates_integrity_of  :image
  validates_processing_of :image  
  
  has_many :deeds
  has_many :requests
  has_many :blogs
  

  private
    def avatar_size_validation
      errors[:image] << "debe ser inferior a 1000 KB" if image.size > 1.0.megabytes
    end
  
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :set_area, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /areas
  # GET /areas.json
  def index
    #@areas = Area.all
    @areas = Area.paginate(:page => params[:page], :per_page => 10)

  end

  # GET /areas/1
  # GET /areas/1.json
  def show
  end

  # GET /areas/new
  def new
    @area = Area.new
  end

  # GET /areas/1/edit
  def edit
  end

  # POST /areas
  # POST /areas.json
  def create
    @area = Area.new(area_params)

    respond_to do |format|
      if @area.save
        format.html { redirect_to @area, notice: 'Area was successfully created.' }
        format.json { render :show, status: :created, location: @area }
      else
        format.html { render :new }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /areas/1
  # PATCH/PUT /areas/1.json
  def update
    respond_to do |format|
      if @area.update(area_params)
        format.html { redirect_to @area, notice: 'Area was successfully updated.' }
        format.json { render :show, status: :ok, location: @area }
      else
        format.html { render :edit }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /areas/1
  # DELETE /areas/1.json
  def destroy
    @area.destroy
    respond_to do |format|
      format.html { redirect_to areas_url, notice: 'Area was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_area
      @area = Area.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def area_params
      params.require(:area).permit(:title, :description)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/profile_teams_controller.rb
class ProfileTeamsController < ApplicationController
  before_action :set_profile_team, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /profile_teams
  # GET /profile_teams.json
  def index
    #@profile_teams = ProfileTeam.all
    @profile_teams = ProfileTeam.paginate(:page => params[:page], :per_page => 5)

  end

  # GET /profile_teams/1
  # GET /profile_teams/1.json
  def show
  end

  # GET /profile_teams/new
  def new
    @profile_team = ProfileTeam.new
  end

  # GET /profile_teams/1/edit
  def edit
  end

  # POST /profile_teams
  # POST /profile_teams.json
  def create
    @profile_team = ProfileTeam.new(profile_team_params)

    respond_to do |format|
      if @profile_team.save
        format.html { redirect_to @profile_team, notice: 'Profile team was successfully created.' }
        format.json { render :show, status: :created, location: @profile_team }
      else
        format.html { render :new }
        format.json { render json: @profile_team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profile_teams/1
  # PATCH/PUT /profile_teams/1.json
  def update
    respond_to do |format|
      if @profile_team.update(profile_team_params)
        format.html { redirect_to @profile_team, notice: 'Profile team was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile_team }
      else
        format.html { render :edit }
        format.json { render json: @profile_team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profile_teams/1
  # DELETE /profile_teams/1.json
  def destroy
    @profile_team.destroy
    respond_to do |format|
      format.html { redirect_to profile_teams_url, notice: 'Profile team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile_team
      @profile_team = ProfileTeam.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_team_params
      params.require(:profile_team).permit(:name, :email, :phone, :celular, :anexo, :address_work, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/deeds_helper.rb
module DeedsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profile_teams_helper.rb
module ProfileTeamsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/profile_teams/_form.html.erb
<%= render "layouts/menu_sin_login"%>
<%= render "home/dashboard"%>
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="well fondo-form">
        <%= form_for(@profile_team) do |f| %>
          <% if @profile_team.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@profile_team.errors.count, "error") %> prohibited this profile_team from being saved:</h2>
              <ul>
              <% @profile_team.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
              </ul>
            </div>
        <% end %>
        
        <div class="form-group">
    <%= f.label :name, 'Nombre' %><br>
    <%= f.text_field :name, class:"form-control", placeholder:"Nombre Apellido" %>
  </div>
  <div class="form-group">
    <%= f.label :email %><br>
    <%= f.text_field :email, class:"form-control", placeholder:"Correo Electrónico" %>
  </div>
  <div class="form-group">
    <%= f.label :phone, 'Teléfono Directo' %><br>
    <%= f.text_field :phone, class:"form-control title_ld", placeholder:"Teléfono Directo" %>
  </div>
  <div class="form-group">
    <%= f.label :celular %><br>
    <%= f.text_field :celular, class:"form-control", placeholder:"Celular" %>
  </div>
  <div class="form-group">
    <%= f.label :anexo %><br>
    <%= f.text_field :anexo, class:"form-control", placeholder:"Cód. Anexo Directo" %>
  </div>
  <div class="form-group">
    <%= f.label :address_work, 'Dirección Laboral' %><br>
    <%= f.text_field :address_work, class:"form-control", placeholder:"Dirección Laboral" %>
  </div>
  <div class="form-group">
    <%= f.label :image, 'Imagen (jpg,png,jpeg) ' %><br>
    <%= f.file_field :image , class: "form-control"%>
  </div>
  <div class="row pull-right">
    <div class="col-md-12">
      <div class="actions form-group">
        <%= f.submit 'Ingresar Datos', class: "btn btn-success" %>
      </div>
    </div>
  </div>
<% end %>
  
</div>

      </div>
    </div>
  </div>


 

app/views/profile_teams/edit.html.erb
<h1>Editing Profile Team</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile_team %> |
<%= link_to 'Back', profile_teams_path %>

app/views/profile_teams/index.html.erb
<%= render "home/dashboard"%>
<div class="container">
  <div class="row pull-right">
    <div class="col-md-12">
      <a href="<%= new_profile_team_path %>" class="btn btn-info">(+) Nuevo Miembro Equipo </a>
    </div>
  </div>
</div>
<div class="container">
  <h1>Listado miembros Calypso</h1>
<div class="table-responsive">
  <table class="table table-bordered table-hover">
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Email</th>
        <th>Teléfono</th>
        <th>Celular</th>
        <th>Anexo</th>
        <th>Lugar Oficina</th>
        <th>Foto</th>
        <th colspan="3">Opciones</th>
      </tr>
    </thead>
  
    <tbody>
      <% @profile_teams.each do |profile_team| %>
        <tr>
          <td><%= profile_team.name %></td>
          <td><%= profile_team.email %></td>
          <td><%= profile_team.phone %></td>
          <td><%= profile_team.celular %></td>
          <td><%= profile_team.anexo %></td>
          <td><%= profile_team.address_work %></td>
          <td><%= image_tag profile_team.image.url(:extra_thumb).to_s, class: "img-responsive" %></td>
          <td>
            <%= link_to 'Ver', profile_team, class:"btn btn-info" %>
            <%= link_to 'Editar', edit_profile_team_path(profile_team), class:"btn btn-warning" %>
            <%= link_to 'Eliminar', profile_team, method: :delete, data: { confirm: '¿Estás seguro?' }, class:"btn btn-danger" %>
          </td>
        </tr>
      <% end %>
    </tbody>
</table>
  
</div>
</div>

app/views/profile_teams/new.html.erb
<h1>New Profile Team</h1>

<%= render 'form' %>

<%= link_to 'Back', profile_teams_path %>

app/views/profile_teams/show.html.erb
<%= render "layouts/menu_sin_login"%>
<%= render "home/dashboard"%>
<div class="container">
  <div class="row">
    <div class ="col-md-6 col-md-offset-6">
      <div class="well fondo-form">
        <% if notice %>
         <p class="notice"><%= notice %></p>
        <% elsif alert %>  
         <p class="alert"><%= alert %></p>
        <% end %>  
        <h2>Se han ingresado los siguientes datos.</h2>
      </div>
    </div>
  </div>
</div>

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @profile_team.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @profile_team.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @profile_team.phone %>
</p>

<p>
  <strong>Celular:</strong>
  <%= @profile_team.celular %>
</p>

<p>
  <strong>Anexo:</strong>
  <%= @profile_team.anexo %>
</p>

<p>
  <strong>Address work:</strong>
  <%= @profile_team.address_work %>
</p>

<p>
  <strong>Image:</strong>
  <%= @profile_team.image %>
</p>

<%= link_to 'Edit', edit_profile_team_path(@profile_team) %> |
<%= link_to 'Back', profile_teams_path %>