config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  resources :review_scheduled_tasks
  resources :tasks
  resources :profile_teams
  resources :requests
  resources :categories
  resources :deeds do
    collection do
    match 'search' => 'welcome#search', via: [:get, :post], as: :search
    end
  end
  resources :areas

  get 'welcome/noticias'
  get 'welcome/home'
  get 'welcome/hitos'
  get 'welcome/proyectos'
  get 'welcome/contingencia'
  get 'welcome/equipo'
  get 'welcome/administracion'
  

 devise_for :users
 
   root 'welcome#home'
   
  
    

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/area.rb
class Area < ActiveRecord::Base
    
    has_many :deeds
    has_many :requests
    has_many :blogs
end

app/models/blog.rb
class Blog < ActiveRecord::Base
    
  validates_presence_of :title, :fecha, :noticia, :category_id
  #validates_processing_of :foto,
  validate :image_size_validation
 
  mount_uploader :foto, FotoUploader
  
  belongs_to :category, foreign_key: "category_id"
  belongs_to :user, foreign_key: "user_id"
  
  
  private
  def image_size_validation
    errors[:foto] << "should be less than 500KB" if foto.size > 0.5.megabytes
  end
  
  
  
end

app/models/category.rb
class Category < ActiveRecord::Base
    
    has_many :blogs
end

app/models/deed.rb
class Deed < ActiveRecord::Base
    
    validates_presence_of :title, :date_deed, :benefit, :area_id
    validates_length_of :title, :minimum => 3
    
    belongs_to :area, foreign_key: "area_id"
    belongs_to :user, foreign_key: "id_user"
    default_scope -> { order(date_deed: :desc) }
    

  def publish_month
    date_deed.strftime("%B %Y")
  end
  def week
   date_deed.strftime('%Y-%W')
  end
  
end

app/models/profile_team.rb
class ProfileTeam < ActiveRecord::Base
    
    validates :name, presence: true
    validates :email, presence: true
    validates :anexo, presence: true
    
    
    mount_uploader :image, ImageUploader
end

app/models/request.rb
class Request < ActiveRecord::Base
    
    mount_uploader :image, ImageUploader
    
    validates :title, presence: true
    validates :area_id, presence: true
    validates :usuario, presence: true
    validates :description, presence: true
    validates :date_request, presence: true
    
    validates_presence_of   :image
    validates_integrity_of  :image
    validates_processing_of :image 
    
    belongs_to :area, foreign_key: "area_id"
    
    private
    def image_size_validation
      errors[:image] << "debe ser inferior a 1000 KB" if image.size > 1.0.megabytes
    end
   
end

app/models/review_scheduled_task.rb
class ReviewScheduledTask < ActiveRecord::Base
end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  mount_uploader :image, ImageUploader
  #mount_uploader :image, ImageUploader
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :timeoutable

  # User Avatar Validation
  validates_presence_of   :image
  validates_integrity_of  :image
  validates_processing_of :image  
  
  has_many :deeds
  has_many :requests
  has_many :blogs
  

  private
    def avatar_size_validation
      errors[:image] << "debe ser inferior a 1000 KB" if image.size > 1.0.megabytes
    end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/review_scheduled_tasks_controller.rb
class ReviewScheduledTasksController < ApplicationController
  before_action :set_review_scheduled_task, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /review_scheduled_tasks
  # GET /review_scheduled_tasks.json
  def index
    #@review_scheduled_tasks = ReviewScheduledTask.all
    @review_scheduled_tasks = ReviewScheduledTask.paginate(:page => params[:page], :per_page => 10)
  end

  # GET /review_scheduled_tasks/1
  # GET /review_scheduled_tasks/1.json
  def show
  end

  # GET /review_scheduled_tasks/new
  def new
    @review_scheduled_task = ReviewScheduledTask.new
  end

  # GET /review_scheduled_tasks/1/edit
  def edit
  end

  # POST /review_scheduled_tasks
  # POST /review_scheduled_tasks.json
  def create
    @review_scheduled_task = ReviewScheduledTask.new(review_scheduled_task_params)
    @review_scheduled_task.user_id = current_user.id

    respond_to do |format|
      if @review_scheduled_task.save
        format.html { redirect_to @review_scheduled_task, notice: 'Review scheduled task was successfully created.' }
        format.json { render :show, status: :created, location: @review_scheduled_task }
      else
        format.html { render :new }
        format.json { render json: @review_scheduled_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /review_scheduled_tasks/1
  # PATCH/PUT /review_scheduled_tasks/1.json
  def update
    respond_to do |format|
      if @review_scheduled_task.update(review_scheduled_task_params)
        format.html { redirect_to @review_scheduled_task, notice: 'Review scheduled task was successfully updated.' }
        format.json { render :show, status: :ok, location: @review_scheduled_task }
      else
        format.html { render :edit }
        format.json { render json: @review_scheduled_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /review_scheduled_tasks/1
  # DELETE /review_scheduled_tasks/1.json
  def destroy
    @review_scheduled_task.destroy
    respond_to do |format|
      format.html { redirect_to review_scheduled_tasks_url, notice: 'Review scheduled task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review_scheduled_task
      @review_scheduled_task = ReviewScheduledTask.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_scheduled_task_params
      params.require(:review_scheduled_task).permit(:date, :task_id, :start, :end, :observation, :comment_to_day, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/deeds_helper.rb
module DeedsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/review_scheduled_tasks_helper.rb
module ReviewScheduledTasksHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/review_scheduled_tasks/_form.html.erb
<%= form_for(@review_scheduled_task) do |f| %>
  <% if @review_scheduled_task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review_scheduled_task.errors.count, "error") %> prohibited this review_scheduled_task from being saved:</h2>

      <ul>
      <% @review_scheduled_task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :task_id %><br>
    <%= f.text_field :task_id %>
  </div>
  <div class="field">
    <%= f.label :start %><br>
    <%= f.check_box :start %>
  </div>
  <div class="field">
    <%= f.label :end %><br>
    <%= f.check_box :end %>
  </div>
  <div class="field">
    <%= f.label :observation %><br>
    <%= f.text_area :observation %>
  </div>
  <div class="field">
    <%= f.label :comment_to_day %><br>
    <%= f.text_area :comment_to_day %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/review_scheduled_tasks/edit.html.erb
<h1>Editing Review Scheduled Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @review_scheduled_task %> |
<%= link_to 'Back', review_scheduled_tasks_path %>

app/views/review_scheduled_tasks/index.html.erb
<%= render "home/dashboard"%>
<div class="container">
  <h1>Revisiones Scheduled Task</h1>
     <div class="row pull-right">
      <div class="col-md-12">
        <a href="<%= new_review_scheduled_task_path %>" class="btn btn-info">(+) Nueva Tarea</a>
      </div>
    </div>
  <table class="table table-bordered table-hover">
    <thead>
      <tr>
        <th>Fecha</th>
        <th>Task</th>
        <th>Inicio</th>
        <th>Fin</th>
        <th>Observaciones</th>
        <th>Comentario General</th>
        <th>User ID</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @review_scheduled_tasks.each do |review_scheduled_task| %>
        <tr>
          <td><%= review_scheduled_task.date %></td>
          <td><%= review_scheduled_task.task_id %></td>
          <td><%= review_scheduled_task.start %></td>
          <td><%= review_scheduled_task.end %></td>
          <td><%= review_scheduled_task.observation %></td>
          <td><%= review_scheduled_task.comment_to_day %></td>
          <td><%= review_scheduled_task.user_id %></td>
          <td>
            <%= link_to 'Show', review_scheduled_task %>
            <%= link_to 'Edit', edit_review_scheduled_task_path(review_scheduled_task) %>
            <%= link_to 'Destroy', review_scheduled_task, method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
          
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div class="row pull-right">
  <div class="col-md-12">
    <%= will_paginate @review_scheduled_task, renderer: BootstrapPagination::Rails %>    
  </div>
</div>

app/views/review_scheduled_tasks/new.html.erb
<%= render "layouts/menu_sin_login"%>
<%= render "home/dashboard"%>
<div class="container">
  <h1>Registrar una nueva Review Scheduled Task</h1>
    <div class="row pull-right">
      <div class="col-md-12">
        <%= link_to '<< Volver', review_scheduled_tasks_path, class: "btn btn-info" %>
      </div>
    </div>
    <%= render 'form' %>
</div>

app/views/review_scheduled_tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @review_scheduled_task.date %>
</p>

<p>
  <strong>Task:</strong>
  <%= @review_scheduled_task.task_id %>
</p>

<p>
  <strong>Start:</strong>
  <%= @review_scheduled_task.start %>
</p>

<p>
  <strong>End:</strong>
  <%= @review_scheduled_task.end %>
</p>

<p>
  <strong>Observation:</strong>
  <%= @review_scheduled_task.observation %>
</p>

<p>
  <strong>Comment to day:</strong>
  <%= @review_scheduled_task.comment_to_day %>
</p>

<p>
  <strong>User:</strong>
  <%= @review_scheduled_task.user_id %>
</p>

<%= link_to 'Edit', edit_review_scheduled_task_path(@review_scheduled_task) %> |
<%= link_to 'Back', review_scheduled_tasks_path %>